#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App3.Resource", IsApplication=true)]

namespace App3
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int face = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int face_2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int fatality = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int sad = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050009
			public const int buttonQuantityMinus = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int buttonQuantityPlus = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int imageButtonFirstFace = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int imageButtonFourthFace = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int imageButtonSecondFace = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int imageButtonThirdFace = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int textQuantity = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int textSelectQuantityPerson = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int textSelected = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MenuAlcohole = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Quantity = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
