#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App3.Resource", IsApplication=true)]

namespace App3
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int face = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int face_2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int fatality = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int pilsner = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int sad = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050010
			public const int btnNext = 2131034128;
			
			// aapt resource value: 0x7f050017
			public const int buttonNext = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int buttonQuantityMinus = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int buttonQuantityPlus = 2131034133;
			
			// aapt resource value: 0x7f050003
			public const int demoImageView = 2131034115;
			
			// aapt resource value: 0x7f05000c
			public const int imageButtonFirstFace = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int imageButtonFourthFace = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int imageButtonSecondFace = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int imageButtonThirdFace = 2131034126;
			
			// aapt resource value: 0x7f050002
			public const int listSelected = 2131034114;
			
			// aapt resource value: 0x7f050011
			public const int listView = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int textQuantity = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int textSelectQuantityPerson = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int textSelected = 2131034130;
			
			// aapt resource value: 0x7f05000b
			public const int textSelectedAlcoholPercent = 2131034123;
			
			// aapt resource value: 0x7f050001
			public const int textSelectedCountPeople = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int textSelectedDiscription = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int textSelectedName = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int textSelectedStatePeople = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int textSelectedVolume = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int textView1 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int textView2 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int textView3 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int textView4 = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LastWindow = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListViewAlcohole = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ListViewLastWindow = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MenuAlcohole = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Quantity = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
